name: Hexo

on:
  push:
    branches:
      - hexo

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Hexo build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pandoc -y
          npm install hexo-cli -g
          npm install

      - name: Generate files
        run: |
          hexo clean
          hexo generate

      - name: Deploy blog
        run: |
          git config --global user.name "wangzihe"
          git config --global user.email "wingzinker@outlook.com"
          hexo deploy