name: Hexo

on:
  push:
    branches:
      - hexo

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Hexo build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache Node Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.OS}}-npm-caches-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: Generate files
        run: |
          hexo clean
          hexo generate

      - name: Deploy blog
        run: |
        cd ./public && git init && git add .
        git config --local user.name "wangzihe"
        git config --local user.email "wingzinker@outlook.com"
        git add -A
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/wangzihe1996/wangzihe1996.github.io" master:master